-- =====================================================================
--  CANGUARD K9 — MODELO DE DATOS
--  PostgreSQL 15+ / UTF8
--  Nomenclatura PascalCase
--
--  Autora: María Fernanda Otero Rodríguez
--  Universidad Piloto de Colombia — Ingeniería de Sistemas
--
--  CONVENCIONES DE NOMENCLATURA
--    Tablas .......... PascalCase singular          Canino, CaninoVacuna
--    Columnas ........ PascalCase                   FechaNacimiento
--    Llave primaria .. Id + nombre de la entidad    IdCanino
--    Llave foránea ... idéntica a la PK que apunta  IdCanino
--    Vistas .......... Vw + nombre                  VwBinomioVigente
--    Restricciones ... Fk/Uq/Ix/Ck + Tabla + Campo  FkBinomioCanino
--
--  NOTA POSTGRESQL: los nombres se escriben sin comillas, por eso PostgreSQL
--  los guarda en minúscula (Canino -> canino, IdCanino -> idcanino). En el
--  código se pueden seguir escribiendo en PascalCase: el motor los convierte.
--
--  Equivalencias respecto a la versión MySQL/MariaDB:
--    AUTO_INCREMENT ............ GENERATED BY DEFAULT AS IDENTITY
--    ENUM('a','b') ............. VARCHAR + CHECK (col IN ('a','b'))
--    TINYINT / TINYINT(1) ...... SMALLINT
--    DATETIME .................. TIMESTAMP
--    LONGTEXT + JSON_VALID ..... JSONB
--    ON UPDATE CURRENT_TIMESTAMP trigger fn_fecha_modificacion()
--    INDEX dentro de la tabla .. CREATE INDEX aparte
--    INSERT IGNORE ............. INSERT ... ON CONFLICT DO NOTHING
--
--  Este script crea la base desde cero y se puede ejecutar varias veces.
-- =====================================================================

-- Función compartida que reemplaza "ON UPDATE CURRENT_TIMESTAMP" de MySQL:
-- cada vez que se actualiza una fila, pone la fecha actual en FechaModificacion.
CREATE OR REPLACE FUNCTION fn_fecha_modificacion() RETURNS TRIGGER AS $$
BEGIN
    NEW.FechaModificacion = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =====================================================================
--  S1. ACCESO Y SEGURIDAD              (RF-01, RF-02, RF-03)
-- =====================================================================

CREATE TABLE IF NOT EXISTS Entidad (
    IdEntidad        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RazonSocial      VARCHAR(255) NOT NULL,
    NitCif           VARCHAR(50)  NOT NULL,
    TipoInstitucion  VARCHAR(20)  NOT NULL DEFAULT 'vigilancia_privada'
                     CHECK (TipoInstitucion IN ('policia','militar','vigilancia_privada',
                                                'bomberos','defensa_civil','otra')),
    Email            VARCHAR(150) NULL,
    Telefono         VARCHAR(30)  NULL,
    Pais             VARCHAR(10)  NOT NULL DEFAULT 'CO',
    Departamento     VARCHAR(100) NULL,
    Ciudad           VARCHAR(150) NULL,
    Direccion        VARCHAR(255) NULL,
    LogoPath         VARCHAR(255) NULL,
    Activo           SMALLINT     NOT NULL DEFAULT 1,
    FechaRegistro    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FechaModificacion TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UqEntidadNit UNIQUE (NitCif)
);
CREATE INDEX IF NOT EXISTS IxEntidadActivo ON Entidad (Activo);

CREATE TABLE IF NOT EXISTS Rol (
    IdRol       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Clave       VARCHAR(30)  NOT NULL,
    Nombre      VARCHAR(80)  NOT NULL,
    Descripcion VARCHAR(255) NULL,
    Ambito      VARCHAR(10)  NOT NULL DEFAULT 'entidad'
                CHECK (Ambito IN ('global','entidad')),
    EsFijo      SMALLINT     NOT NULL DEFAULT 0,
    Activo      SMALLINT     NOT NULL DEFAULT 1,
    CONSTRAINT UqRolClave UNIQUE (Clave)
);

CREATE TABLE IF NOT EXISTS Permiso (
    IdPermiso   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Clave       VARCHAR(60) NOT NULL,   -- Canino.Crear, Geo.Ver, ...
    Modulo      VARCHAR(40) NOT NULL,
    Descripcion VARCHAR(255) NULL,
    CONSTRAINT UqPermisoClave UNIQUE (Clave)
);
CREATE INDEX IF NOT EXISTS IxPermisoModulo ON Permiso (Modulo);

CREATE TABLE IF NOT EXISTS RolPermiso (
    IdRol     INT NOT NULL,
    IdPermiso INT NOT NULL,
    PRIMARY KEY (IdRol, IdPermiso),
    CONSTRAINT FkRolPermisoRol     FOREIGN KEY (IdRol)     REFERENCES Rol(IdRol)         ON DELETE CASCADE,
    CONSTRAINT FkRolPermisoPermiso FOREIGN KEY (IdPermiso) REFERENCES Permiso(IdPermiso) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Usuario (
    IdUsuario        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdEntidad        INT          NULL,       -- NULL = super administrador
    IdRol            INT          NOT NULL,
    Rol              VARCHAR(30)  NOT NULL,   -- copia de Rol.Clave para lectura rápida
    Nombre           VARCHAR(150) NOT NULL,
    NombreUsuario    VARCHAR(50)  NOT NULL,
    TipoDocumento    VARCHAR(5)   NOT NULL DEFAULT 'CC'
                     CHECK (TipoDocumento IN ('CC','CE','TI','PA','NIT')),
    Documento        VARCHAR(30)  NOT NULL,
    Nacionalidad     VARCHAR(10)  NULL DEFAULT 'CO',
    Email            VARCHAR(150) NOT NULL,
    Telefono         VARCHAR(30)  NULL,
    Direccion        VARCHAR(150) NULL,
    PasswordHash     VARCHAR(255) NOT NULL,   -- bcrypt / argon2
    FotoPerfilPath   VARCHAR(255) NULL,
    DocIdentidadPath VARCHAR(255) NULL,
    Estado           VARCHAR(10)  NOT NULL DEFAULT 'activo'
                     CHECK (Estado IN ('activo','inactivo','bloqueado')),
    IntentosFallidos SMALLINT     NOT NULL DEFAULT 0,
    UltimoAcceso     TIMESTAMP    NULL,
    FechaRegistro    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FechaModificacion TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UqUsuarioNombreUsuario UNIQUE (NombreUsuario),
    CONSTRAINT UqUsuarioEmail         UNIQUE (Email),
    CONSTRAINT UqUsuarioDocumento     UNIQUE (TipoDocumento, Documento),
    CONSTRAINT FkUsuarioEntidad FOREIGN KEY (IdEntidad) REFERENCES Entidad(IdEntidad) ON DELETE RESTRICT,
    CONSTRAINT FkUsuarioRol     FOREIGN KEY (IdRol)     REFERENCES Rol(IdRol)         ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS IxUsuarioEntidadRol ON Usuario (IdEntidad, Rol);

-- Reemplaza las columnas TokenRecuperacion / ExpiracionToken que estaban
-- dentro de Usuario: un usuario puede solicitar varios restablecimientos
-- y conviene guardar el rastro de cada solicitud.
CREATE TABLE IF NOT EXISTS TokenRecuperacion (
    IdTokenRecuperacion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdUsuario    INT         NOT NULL,
    TokenHash    CHAR(64)    NOT NULL,
    ExpiraEn     TIMESTAMP   NOT NULL,
    UsadoEn      TIMESTAMP   NULL,
    IpSolicitud  VARCHAR(45) NULL,
    FechaRegistro TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UqTokenHash UNIQUE (TokenHash),
    CONSTRAINT FkTokenUsuario FOREIGN KEY (IdUsuario) REFERENCES Usuario(IdUsuario) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS IxTokenUsuario ON TokenRecuperacion (IdUsuario, ExpiraEn);

CREATE TABLE IF NOT EXISTS Auditoria (
    IdAuditoria    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdUsuario      INT          NULL,
    IdEntidad      INT          NULL,
    Accion         VARCHAR(15)  NOT NULL
                   CHECK (Accion IN ('CREATE','UPDATE','DELETE','LOGIN','LOGOUT',
                                     'LOGIN_FALLIDO','EXPORT','ASIGNAR','BAJA')),
    TablaAfectada  VARCHAR(60)  NOT NULL,
    IdRegistro     INT          NULL,
    DatosAntes     JSONB        NULL,
    DatosDespues   JSONB        NULL,
    Ip             VARCHAR(45)  NULL,
    UserAgent      VARCHAR(255) NULL,
    FechaHora      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT FkAuditoriaUsuario FOREIGN KEY (IdUsuario) REFERENCES Usuario(IdUsuario) ON DELETE SET NULL,
    CONSTRAINT FkAuditoriaEntidad FOREIGN KEY (IdEntidad) REFERENCES Entidad(IdEntidad) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS IxAuditoriaUsuario ON Auditoria (IdUsuario, FechaHora);
CREATE INDEX IF NOT EXISTS IxAuditoriaTabla   ON Auditoria (TablaAfectada, IdRegistro);
CREATE INDEX IF NOT EXISTS IxAuditoriaEntidad ON Auditoria (IdEntidad, FechaHora);

-- =====================================================================
--  S2. INVENTARIO K9                   (RF-04 a RF-12)
-- =====================================================================

CREATE TABLE IF NOT EXISTS ProgramaK9 (
    IdPrograma       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdEntidad        INT          NULL,       -- NULL = programa global
    Clave            VARCHAR(50)  NOT NULL,
    Nombre           VARCHAR(150) NOT NULL,
    Descripcion      TEXT         NULL,
    DuracionHoras    SMALLINT     NULL,
    Nivel            VARCHAR(12)  NULL
                     CHECK (Nivel IN ('basico','intermedio','avanzado')),
    VigenciaMeses    SMALLINT     NULL,       -- validez de la certificación
    Icono            VARCHAR(60)  NOT NULL DEFAULT 'bi-mortarboard-fill',
    Color            VARCHAR(20)  NOT NULL DEFAULT '#b8860b',
    ImagenFondoPath  VARCHAR(255) NULL,
    EsFijo           SMALLINT     NOT NULL DEFAULT 0,
    Activo           SMALLINT     NOT NULL DEFAULT 1,
    FechaRegistro    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UqProgramaClave UNIQUE (Clave),
    CONSTRAINT FkProgramaEntidad FOREIGN KEY (IdEntidad) REFERENCES Entidad(IdEntidad) ON DELETE CASCADE
);

-- La edad NO se almacena: es un dato derivado que se desactualiza solo.
-- Se calcula con AGE(CURRENT_DATE, FechaNacimiento) (ver VwCaninoDetalle).
-- Tampoco se almacenan UltimaVacunacion / ProximaVacunacion / NombreVacuna:
-- viven en CaninoVacuna y se consultan por VwCaninoVacunacion.
CREATE TABLE IF NOT EXISTS Canino (
    IdCanino             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdEntidad            INT          NOT NULL,
    IdPrograma           INT          NULL,
    IdGuiaActual         INT          NULL,   -- copia del binomio vigente
    CodigoUnico          VARCHAR(30)  NOT NULL,
    Nombre               VARCHAR(100) NOT NULL,
    Raza                 VARCHAR(100) NULL,
    Genero               VARCHAR(6)   NULL
                         CHECK (Genero IN ('macho','hembra')),
    FechaNacimiento      DATE         NULL,
    ChipNumero           VARCHAR(50)  NULL,
    NumRegistro          VARCHAR(50)  NULL,
    ColorPelaje          VARCHAR(100) NULL,
    PesoKg               DECIMAL(5,2) NULL,
    TallaCm              SMALLINT     NULL,
    Especialidad         VARCHAR(100) NULL,   -- espejo de ProgramaK9.Clave
    Estado               VARCHAR(15)  NOT NULL DEFAULT 'entrenamiento'
                         CHECK (Estado IN ('activo','entrenamiento','descanso',
                                           'incapacitado','retirado','baja')),
    FotoPath             VARCHAR(255) NULL,
    Procedencia          VARCHAR(150) NULL,
    FechaIngreso         DATE         NULL,
    Observaciones        TEXT         NULL,
    HistorialClinicoPath VARCHAR(255) NULL,
    MotivoBaja           VARCHAR(60)  NULL,
    JustificacionBaja    TEXT         NULL,
    FechaBaja            DATE         NULL,
    CartaBajaPath        VARCHAR(255) NULL,
    FechaRegistro        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FechaModificacion    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UqCaninoCodigo UNIQUE (IdEntidad, CodigoUnico),
    CONSTRAINT UqCaninoChip   UNIQUE (ChipNumero),
    CONSTRAINT FkCaninoEntidad  FOREIGN KEY (IdEntidad)    REFERENCES Entidad(IdEntidad)      ON DELETE RESTRICT,
    CONSTRAINT FkCaninoPrograma FOREIGN KEY (IdPrograma)   REFERENCES ProgramaK9(IdPrograma)  ON DELETE SET NULL,
    CONSTRAINT FkCaninoGuia     FOREIGN KEY (IdGuiaActual) REFERENCES Usuario(IdUsuario)      ON DELETE SET NULL,
    CONSTRAINT CkCaninoBaja CHECK (Estado <> 'baja' OR FechaBaja IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS IxCaninoEntidadEstado ON Canino (IdEntidad, Estado);
CREATE INDEX IF NOT EXISTS IxCaninoPrograma      ON Canino (IdPrograma);
CREATE INDEX IF NOT EXISTS IxCaninoGuia          ON Canino (IdGuiaActual);

CREATE TABLE IF NOT EXISTS CaninoEstado (
    IdCaninoEstado    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdCanino          INT          NOT NULL,
    EstadoAnterior    VARCHAR(20)  NULL,
    EstadoNuevo       VARCHAR(20)  NOT NULL,
    Motivo            VARCHAR(255) NULL,
    FechaCambio       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IdUsuarioRegistra INT          NULL,
    CONSTRAINT FkCaninoEstadoCanino  FOREIGN KEY (IdCanino)          REFERENCES Canino(IdCanino)   ON DELETE RESTRICT,
    CONSTRAINT FkCaninoEstadoUsuario FOREIGN KEY (IdUsuarioRegistra) REFERENCES Usuario(IdUsuario) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS IxCaninoEstadoCanino ON CaninoEstado (IdCanino, FechaCambio);

CREATE TABLE IF NOT EXISTS GuiaCertificacion (
    IdGuiaCertificacion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdUsuario        INT          NOT NULL,
    Nombre           VARCHAR(150) NOT NULL,
    EntidadEmisora   VARCHAR(150) NULL,
    FechaEmision     DATE         NULL,
    FechaVencimiento DATE         NULL,
    DocumentoPath    VARCHAR(255) NULL,
    FechaRegistro    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FkGuiaCertUsuario FOREIGN KEY (IdUsuario) REFERENCES Usuario(IdUsuario) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS IxGuiaCertUsuario ON GuiaCertificacion (IdUsuario, FechaVencimiento);

-- Tabla clave del modelo: convierte la relación guía-canino en una entidad
-- con vigencia temporal. La columna generada Vigente vale 1 mientras el
-- binomio esté abierto y NULL cuando se cierra; como los NULL no colisionan
-- en un índice UNIQUE, el motor garantiza un solo binomio abierto por canino.
CREATE TABLE IF NOT EXISTS Binomio (
    IdBinomio         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdCanino          INT          NOT NULL,
    IdGuia            INT          NOT NULL,
    IdEntidad         INT          NOT NULL,
    FechaInicio       DATE         NOT NULL,
    FechaFin          DATE         NULL,
    MotivoFin         VARCHAR(255) NULL,
    Observaciones     TEXT         NULL,
    IdUsuarioRegistra INT          NULL,
    FechaRegistro     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Vigente           SMALLINT GENERATED ALWAYS AS
                      (CASE WHEN FechaFin IS NULL THEN 1 END) STORED,
    CONSTRAINT UqBinomioVigente UNIQUE (IdCanino, Vigente),
    CONSTRAINT FkBinomioCanino  FOREIGN KEY (IdCanino)          REFERENCES Canino(IdCanino)   ON DELETE RESTRICT,
    CONSTRAINT FkBinomioGuia    FOREIGN KEY (IdGuia)            REFERENCES Usuario(IdUsuario) ON DELETE RESTRICT,
    CONSTRAINT FkBinomioEntidad FOREIGN KEY (IdEntidad)         REFERENCES Entidad(IdEntidad) ON DELETE RESTRICT,
    CONSTRAINT FkBinomioUsuario FOREIGN KEY (IdUsuarioRegistra) REFERENCES Usuario(IdUsuario) ON DELETE SET NULL,
    CONSTRAINT CkBinomioFechas CHECK (FechaFin IS NULL OR FechaFin >= FechaInicio)
);
CREATE INDEX IF NOT EXISTS IxBinomioGuia    ON Binomio (IdGuia, FechaInicio);
CREATE INDEX IF NOT EXISTS IxBinomioEntidad ON Binomio (IdEntidad);

-- =====================================================================
--  SALUD Y BIENESTAR ANIMAL   (Ley 1774 de 2016, Ley 2454 de 2025)
-- =====================================================================

CREATE TABLE IF NOT EXISTS CaninoVacuna (
    IdCaninoVacuna   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdCanino         INT          NOT NULL,
    NombreVacuna     VARCHAR(100) NOT NULL,
    Lote             VARCHAR(50)  NULL,
    FechaAplicacion  DATE         NOT NULL,
    FechaVencimiento DATE         NULL,
    Veterinario      VARCHAR(150) NULL,
    Notas            TEXT         NULL,
    ComprobantePath  VARCHAR(255) NULL,
    FechaRegistro    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FkVacunaCanino FOREIGN KEY (IdCanino) REFERENCES Canino(IdCanino) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS IxVacunaCanino      ON CaninoVacuna (IdCanino, FechaAplicacion);
CREATE INDEX IF NOT EXISTS IxVacunaVencimiento ON CaninoVacuna (FechaVencimiento);

CREATE TABLE IF NOT EXISTS AtencionVeterinaria (
    IdAtencionVeterinaria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdCanino          INT          NOT NULL,
    Tipo              VARCHAR(20)  NOT NULL
                      CHECK (Tipo IN ('consulta','urgencia','cirugia','tratamiento',
                                      'control','desparasitacion','revision_bienestar')),
    Fecha             DATE         NOT NULL,
    Veterinario       VARCHAR(150) NULL,
    Diagnostico       TEXT         NULL,
    Tratamiento       TEXT         NULL,
    DiasIncapacidad   SMALLINT     NULL,
    PesoKg            DECIMAL(5,2) NULL,
    SoportePath       VARCHAR(255) NULL,
    IdUsuarioRegistra INT          NULL,
    FechaRegistro     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FkAtencionCanino  FOREIGN KEY (IdCanino)          REFERENCES Canino(IdCanino)   ON DELETE RESTRICT,
    CONSTRAINT FkAtencionUsuario FOREIGN KEY (IdUsuarioRegistra) REFERENCES Usuario(IdUsuario) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS IxAtencionCanino ON AtencionVeterinaria (IdCanino, Fecha);

-- =====================================================================
--  S3. TRAZABILIDAD OPERATIVA Y ACADÉMICA   (RF-13 a RF-16)
-- =====================================================================

CREATE TABLE IF NOT EXISTS Curso (
    IdCurso       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdPrograma    INT          NOT NULL,
    IdEntidad     INT          NOT NULL,
    IdInstructor  INT          NULL,
    Nombre        VARCHAR(200) NOT NULL,
    FechaInicio   DATE         NOT NULL,
    FechaFin      DATE         NULL,
    Lugar         VARCHAR(200) NULL,
    Estado        VARCHAR(12)  NOT NULL DEFAULT 'planificado'
                  CHECK (Estado IN ('planificado','en_curso','finalizado','cancelado')),
    Descripcion   TEXT         NULL,
    FechaRegistro TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FkCursoPrograma   FOREIGN KEY (IdPrograma)   REFERENCES ProgramaK9(IdPrograma) ON DELETE RESTRICT,
    CONSTRAINT FkCursoEntidad    FOREIGN KEY (IdEntidad)    REFERENCES Entidad(IdEntidad)     ON DELETE RESTRICT,
    CONSTRAINT FkCursoInstructor FOREIGN KEY (IdInstructor) REFERENCES Usuario(IdUsuario)     ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS IxCursoEntidad ON Curso (IdEntidad, Estado);

CREATE TABLE IF NOT EXISTS CursoInscripcion (
    IdCursoInscripcion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdCurso            INT  NOT NULL,
    IdCanino           INT  NOT NULL,
    IdBinomio          INT  NULL,
    FechaInscripcion   DATE NOT NULL,
    Estado             VARCHAR(12) NOT NULL DEFAULT 'inscrito'
                       CHECK (Estado IN ('inscrito','en_curso','aprobado','no_aprobado','retirado')),
    CalificacionFinal  DECIMAL(5,2) NULL,
    Observaciones      TEXT NULL,
    CONSTRAINT UqInscripcion UNIQUE (IdCurso, IdCanino),
    CONSTRAINT FkInscripcionCurso   FOREIGN KEY (IdCurso)   REFERENCES Curso(IdCurso)     ON DELETE RESTRICT,
    CONSTRAINT FkInscripcionCanino  FOREIGN KEY (IdCanino)  REFERENCES Canino(IdCanino)   ON DELETE RESTRICT,
    CONSTRAINT FkInscripcionBinomio FOREIGN KEY (IdBinomio) REFERENCES Binomio(IdBinomio) ON DELETE SET NULL
);

-- Antes se llamaba cursos_sesiones. Se renombra a Sesion porque cada fila
-- es una sesión de entrenamiento, no un curso.
CREATE TABLE IF NOT EXISTS Sesion (
    IdSesion          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdCurso           INT          NULL,
    IdCanino          INT          NOT NULL,
    IdBinomio         INT          NULL,
    IdEntidad         INT          NULL,
    IdPrograma        INT          NULL,
    IdInstructor      INT          NULL,
    Especialidad      VARCHAR(50)  NOT NULL,   -- espejo de ProgramaK9.Clave
    TipoActividad     VARCHAR(20)  NULL
                      CHECK (TipoActividad IN ('obediencia','adiestramiento','practica',
                                               'evaluacion','socializacion','acondicionamiento')),
    Fecha             DATE         NOT NULL,
    HoraInicio        TIME         NULL,
    DuracionMin       SMALLINT     NULL,
    Lugar             VARCHAR(200) NULL,
    Latitud           DECIMAL(10,8) NULL,
    Longitud          DECIMAL(11,8) NULL,
    Resultado         VARCHAR(30)  NULL,
    Instructor        VARCHAR(150) NULL,       -- texto libre heredado
    Observaciones     TEXT         NULL,
    IdUsuarioRegistra INT          NULL,
    FechaRegistro     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FkSesionCanino     FOREIGN KEY (IdCanino)     REFERENCES Canino(IdCanino)       ON DELETE RESTRICT,
    CONSTRAINT FkSesionCurso      FOREIGN KEY (IdCurso)      REFERENCES Curso(IdCurso)         ON DELETE SET NULL,
    CONSTRAINT FkSesionBinomio    FOREIGN KEY (IdBinomio)    REFERENCES Binomio(IdBinomio)     ON DELETE SET NULL,
    CONSTRAINT FkSesionEntidad    FOREIGN KEY (IdEntidad)    REFERENCES Entidad(IdEntidad)     ON DELETE RESTRICT,
    CONSTRAINT FkSesionPrograma   FOREIGN KEY (IdPrograma)   REFERENCES ProgramaK9(IdPrograma) ON DELETE SET NULL,
    CONSTRAINT FkSesionInstructor FOREIGN KEY (IdInstructor) REFERENCES Usuario(IdUsuario)     ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS IxSesionCanino       ON Sesion (IdCanino, Fecha);
CREATE INDEX IF NOT EXISTS IxSesionEspecialidad ON Sesion (Especialidad, Fecha);
CREATE INDEX IF NOT EXISTS IxSesionEntidad      ON Sesion (IdEntidad, Fecha);

CREATE TABLE IF NOT EXISTS Evaluacion (
    IdEvaluacion   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdCanino       INT          NOT NULL,
    IdSesion       INT          NULL,
    IdCurso        INT          NULL,
    IdEvaluador    INT          NULL,
    Tipo           VARCHAR(15)  NOT NULL
                   CHECK (Tipo IN ('diagnostica','parcial','final','recertificacion')),
    Fecha          DATE         NOT NULL,
    Puntaje        DECIMAL(5,2) NULL,
    PuntajeMaximo  DECIMAL(5,2) NULL DEFAULT 100.00,
    Aprobado       SMALLINT     NULL,
    Criterios      JSONB        NULL,
    Observaciones  TEXT         NULL,
    FechaRegistro  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FkEvaluacionCanino    FOREIGN KEY (IdCanino)    REFERENCES Canino(IdCanino)   ON DELETE RESTRICT,
    CONSTRAINT FkEvaluacionSesion    FOREIGN KEY (IdSesion)    REFERENCES Sesion(IdSesion)   ON DELETE SET NULL,
    CONSTRAINT FkEvaluacionCurso     FOREIGN KEY (IdCurso)     REFERENCES Curso(IdCurso)     ON DELETE SET NULL,
    CONSTRAINT FkEvaluacionEvaluador FOREIGN KEY (IdEvaluador) REFERENCES Usuario(IdUsuario) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS IxEvaluacionCanino ON Evaluacion (IdCanino, Fecha);

CREATE TABLE IF NOT EXISTS Certificacion (
    IdCertificacion   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdCanino          INT          NOT NULL,
    IdPrograma        INT          NOT NULL,
    IdCurso           INT          NULL,
    IdUsuarioRegistra INT          NULL,
    CodigoCertificado VARCHAR(60)  NOT NULL,
    EntidadEmisora    VARCHAR(150) NULL,
    FechaEmision      DATE         NOT NULL,
    FechaVencimiento  DATE         NULL,
    Estado            VARCHAR(12)  NOT NULL DEFAULT 'vigente'
                      CHECK (Estado IN ('vigente','vencida','revocada','suspendida')),
    DocumentoPath     VARCHAR(255) NULL,
    FechaRegistro     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UqCertificacionCodigo UNIQUE (CodigoCertificado),
    CONSTRAINT FkCertificacionCanino   FOREIGN KEY (IdCanino)   REFERENCES Canino(IdCanino)       ON DELETE RESTRICT,
    CONSTRAINT FkCertificacionPrograma FOREIGN KEY (IdPrograma) REFERENCES ProgramaK9(IdPrograma) ON DELETE RESTRICT,
    CONSTRAINT FkCertificacionCurso    FOREIGN KEY (IdCurso)    REFERENCES Curso(IdCurso)         ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS IxCertificacionCanino      ON Certificacion (IdCanino, Estado);
CREATE INDEX IF NOT EXISTS IxCertificacionVencimiento ON Certificacion (FechaVencimiento);

CREATE TABLE IF NOT EXISTS Operacion (
    IdOperacion       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdEntidad         INT          NOT NULL,
    IdCanino          INT          NOT NULL,
    IdBinomio         INT          NULL,
    IdUsuarioRegistra INT          NULL,
    TipoOperacion     VARCHAR(20)  NOT NULL
                      CHECK (TipoOperacion IN ('patrullaje','requisa','busqueda_rescate','deteccion',
                                               'control_perimetral','escolta','apoyo_judicial','simulacro')),
    CodigoMision      VARCHAR(50)  NULL,
    FechaInicio       TIMESTAMP    NOT NULL,
    FechaFin          TIMESTAMP    NULL,
    Ubicacion         VARCHAR(255) NULL,
    Latitud           DECIMAL(10,8) NULL,
    Longitud          DECIMAL(11,8) NULL,
    Descripcion       TEXT         NULL,
    Resultado         VARCHAR(15)  NULL
                      CHECK (Resultado IN ('exitosa','parcial','sin_hallazgos','abortada')),
    Hallazgos         TEXT         NULL,
    FechaRegistro     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FkOperacionCanino  FOREIGN KEY (IdCanino)  REFERENCES Canino(IdCanino)   ON DELETE RESTRICT,
    CONSTRAINT FkOperacionBinomio FOREIGN KEY (IdBinomio) REFERENCES Binomio(IdBinomio) ON DELETE SET NULL,
    CONSTRAINT FkOperacionEntidad FOREIGN KEY (IdEntidad) REFERENCES Entidad(IdEntidad) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS IxOperacionCanino  ON Operacion (IdCanino, FechaInicio);
CREATE INDEX IF NOT EXISTS IxOperacionEntidad ON Operacion (IdEntidad, FechaInicio);

-- Línea de tiempo unificada del canino: toda acción relevante escribe aquí
-- una fila, de modo que el historial se consulta con una sola query.
CREATE TABLE IF NOT EXISTS Evento (
    IdEvento          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdCanino          INT          NOT NULL,
    IdEntidad         INT          NOT NULL,
    IdBinomio         INT          NULL,
    Categoria         VARCHAR(15)  NOT NULL
                      CHECK (Categoria IN ('administrativo','formativo','operativo',
                                           'sanitario','geografico','documental')),
    Tipo              VARCHAR(50)  NOT NULL,
    Titulo            VARCHAR(200) NOT NULL,
    Descripcion       TEXT         NULL,
    FechaHora         TIMESTAMP    NOT NULL,
    UbicacionTexto    VARCHAR(255) NULL,
    Latitud           DECIMAL(10,8) NULL,
    Longitud          DECIMAL(11,8) NULL,
    Resultado         VARCHAR(50)  NULL,
    IdSesion          INT          NULL,
    IdOperacion       INT          NULL,
    IdCertificacion   INT          NULL,
    IdRegistroDocumental INT       NULL,
    IdUsuarioRegistra INT          NULL,
    FechaRegistro     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FkEventoCanino    FOREIGN KEY (IdCanino)          REFERENCES Canino(IdCanino)     ON DELETE RESTRICT,
    CONSTRAINT FkEventoEntidad   FOREIGN KEY (IdEntidad)         REFERENCES Entidad(IdEntidad)   ON DELETE RESTRICT,
    CONSTRAINT FkEventoBinomio   FOREIGN KEY (IdBinomio)         REFERENCES Binomio(IdBinomio)   ON DELETE SET NULL,
    CONSTRAINT FkEventoSesion    FOREIGN KEY (IdSesion)          REFERENCES Sesion(IdSesion)     ON DELETE SET NULL,
    CONSTRAINT FkEventoOperacion FOREIGN KEY (IdOperacion)       REFERENCES Operacion(IdOperacion) ON DELETE SET NULL,
    CONSTRAINT FkEventoUsuario   FOREIGN KEY (IdUsuarioRegistra) REFERENCES Usuario(IdUsuario)   ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS IxEventoCaninoFecha      ON Evento (IdCanino, FechaHora);
CREATE INDEX IF NOT EXISTS IxEventoEntidadCategoria ON Evento (IdEntidad, Categoria, FechaHora);

-- =====================================================================
--  S4. GEOLOCALIZACIÓN                 (RF-17, RF-18)
-- =====================================================================

CREATE TABLE IF NOT EXISTS DispositivoGps (
    IdDispositivo   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdEntidad       INT          NOT NULL,
    IdUsuario       INT          NULL,
    IdCanino        INT          NULL,
    Identificador   VARCHAR(100) NOT NULL,   -- IMEI / UUID / token de app
    Tipo            VARCHAR(12)  NOT NULL DEFAULT 'smartphone'
                    CHECK (Tipo IN ('smartphone','collar_gps','tablet','radio')),
    Modelo          VARCHAR(100) NULL,
    AsignadoA       VARCHAR(10)  NOT NULL DEFAULT 'guia'
                    CHECK (AsignadoA IN ('guia','canino','vehiculo')),
    ApiTokenHash    CHAR(64)     NULL,
    BateriaPct      SMALLINT     NULL,
    UltimaConexion  TIMESTAMP    NULL,
    Activo          SMALLINT     NOT NULL DEFAULT 1,
    FechaRegistro   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UqDispositivoIdentificador UNIQUE (Identificador),
    CONSTRAINT FkDispositivoEntidad FOREIGN KEY (IdEntidad) REFERENCES Entidad(IdEntidad) ON DELETE RESTRICT,
    CONSTRAINT FkDispositivoUsuario FOREIGN KEY (IdUsuario) REFERENCES Usuario(IdUsuario) ON DELETE SET NULL,
    CONSTRAINT FkDispositivoCanino  FOREIGN KEY (IdCanino)  REFERENCES Canino(IdCanino)   ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS IxDispositivoEntidad ON DispositivoGps (IdEntidad, Activo);

CREATE TABLE IF NOT EXISTS Recorrido (
    IdRecorrido  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdEntidad    INT       NOT NULL,
    IdBinomio    INT       NULL,
    IdCanino     INT       NULL,
    IdOperacion  INT       NULL,
    FechaInicio  TIMESTAMP NOT NULL,
    FechaFin     TIMESTAMP NULL,
    DistanciaKm  DECIMAL(8,3) NULL,
    DuracionMin  INT       NULL,
    NumPuntos    INT       NOT NULL DEFAULT 0,
    Estado       VARCHAR(12) NOT NULL DEFAULT 'en_curso'
                 CHECK (Estado IN ('en_curso','finalizado','interrumpido')),
    Notas        TEXT      NULL,
    CONSTRAINT FkRecorridoEntidad   FOREIGN KEY (IdEntidad)   REFERENCES Entidad(IdEntidad)     ON DELETE RESTRICT,
    CONSTRAINT FkRecorridoBinomio   FOREIGN KEY (IdBinomio)   REFERENCES Binomio(IdBinomio)     ON DELETE SET NULL,
    CONSTRAINT FkRecorridoCanino    FOREIGN KEY (IdCanino)    REFERENCES Canino(IdCanino)       ON DELETE SET NULL,
    CONSTRAINT FkRecorridoOperacion FOREIGN KEY (IdOperacion) REFERENCES Operacion(IdOperacion) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS IxRecorridoBinomio ON Recorrido (IdBinomio, FechaInicio);
CREATE INDEX IF NOT EXISTS IxRecorridoEntidad ON Recorrido (IdEntidad, FechaInicio);

-- Tabla de mayor volumen: un binomio reportando cada 10 s genera unas
-- 8.600 filas por jornada. Por eso usa BIGINT y se indexa por tiempo.
CREATE TABLE IF NOT EXISTS Posicion (
    IdPosicion     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdDispositivo  INT           NOT NULL,
    IdEntidad      INT           NOT NULL,
    IdBinomio      INT           NULL,
    IdCanino       INT           NULL,
    IdUsuario      INT           NULL,
    IdRecorrido    INT           NULL,
    Latitud        DECIMAL(10,8) NOT NULL,
    Longitud       DECIMAL(11,8) NOT NULL,
    AltitudM       DECIMAL(7,2)  NULL,
    PrecisionM     DECIMAL(6,2)  NULL,
    VelocidadKmh   DECIMAL(6,2)  NULL,
    RumboGrados    SMALLINT      NULL,
    BateriaPct     SMALLINT      NULL,
    FechaHora      TIMESTAMP     NOT NULL,   -- hora del dispositivo
    RecibidoEn     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FkPosicionDispositivo FOREIGN KEY (IdDispositivo) REFERENCES DispositivoGps(IdDispositivo) ON DELETE RESTRICT,
    CONSTRAINT FkPosicionRecorrido   FOREIGN KEY (IdRecorrido)   REFERENCES Recorrido(IdRecorrido)       ON DELETE SET NULL,
    CONSTRAINT CkPosicionLatitud  CHECK (Latitud  BETWEEN -90  AND 90),
    CONSTRAINT CkPosicionLongitud CHECK (Longitud BETWEEN -180 AND 180)
);
CREATE INDEX IF NOT EXISTS IxPosicionBinomio   ON Posicion (IdBinomio, FechaHora);
CREATE INDEX IF NOT EXISTS IxPosicionRecorrido ON Posicion (IdRecorrido, FechaHora);
CREATE INDEX IF NOT EXISTS IxPosicionEntidad   ON Posicion (IdEntidad, FechaHora);

CREATE TABLE IF NOT EXISTS ZonaInteres (
    IdZona        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdEntidad     INT           NOT NULL,
    Nombre        VARCHAR(150)  NOT NULL,
    Tipo          VARCHAR(15)   NOT NULL
                  CHECK (Tipo IN ('patrullaje','restringida','base','entrenamiento','riesgo')),
    CentroLat     DECIMAL(10,8) NULL,
    CentroLng     DECIMAL(11,8) NULL,
    RadioM        INT           NULL,
    Poligono      JSONB         NULL,
    Color         VARCHAR(20)   NULL,
    Activo        SMALLINT      NOT NULL DEFAULT 1,
    FechaRegistro TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FkZonaEntidad FOREIGN KEY (IdEntidad) REFERENCES Entidad(IdEntidad) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS IxZonaEntidad ON ZonaInteres (IdEntidad, Activo);

CREATE TABLE IF NOT EXISTS Alerta (
    IdAlerta         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdEntidad        INT NOT NULL,
    IdCanino         INT NULL,
    IdBinomio        INT NULL,
    IdZona           INT NULL,
    IdUsuarioLectura INT NULL,
    Tipo             VARCHAR(30) NOT NULL
                     CHECK (Tipo IN ('vacuna_por_vencer','vacuna_vencida','certificacion_por_vencer',
                                     'salida_zona','entrada_zona_restringida','inmovilidad',
                                     'sin_senal','estado_critico','documento_pendiente')),
    Severidad        VARCHAR(10) NOT NULL DEFAULT 'media'
                     CHECK (Severidad IN ('info','media','alta','critica')),
    Mensaje          VARCHAR(255) NOT NULL,
    GeneradaEn       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LeidaEn          TIMESTAMP    NULL,
    Atendida         SMALLINT     NOT NULL DEFAULT 0,
    CONSTRAINT FkAlertaEntidad FOREIGN KEY (IdEntidad) REFERENCES Entidad(IdEntidad)   ON DELETE CASCADE,
    CONSTRAINT FkAlertaCanino  FOREIGN KEY (IdCanino)  REFERENCES Canino(IdCanino)     ON DELETE CASCADE,
    CONSTRAINT FkAlertaZona    FOREIGN KEY (IdZona)    REFERENCES ZonaInteres(IdZona)  ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS IxAlertaEntidad ON Alerta (IdEntidad, Atendida, GeneradaEn);
CREATE INDEX IF NOT EXISTS IxAlertaCanino  ON Alerta (IdCanino);

-- =====================================================================
--  S5. REGISTRO DOCUMENTAL Y AUDIOVISUAL   (RF-19, RF-20)
-- =====================================================================

-- Sustituye a sesion_vision. Separa el archivo (metadatos y hash de
-- integridad) del contenido derivado (transcripción y resumen), y deja
-- constancia de si el resumen fue escrito por una persona o asistido.
CREATE TABLE IF NOT EXISTS RegistroDocumental (
    IdRegistroDocumental INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdEntidad        INT          NOT NULL,
    IdCanino         INT          NOT NULL,
    IdSesion         INT          NULL,
    IdOperacion      INT          NULL,
    IdInstructor     INT          NULL,
    IdUsuarioCarga   INT          NULL,
    Titulo           VARCHAR(200) NOT NULL,
    TipoActividad    VARCHAR(60)  NULL,
    FechaHora        TIMESTAMP    NOT NULL,
    Lugar            VARCHAR(200) NULL,
    ArchivoPath      VARCHAR(255) NOT NULL,
    TipoArchivo      VARCHAR(10)  NOT NULL DEFAULT 'video'
                     CHECK (TipoArchivo IN ('video','audio','imagen','documento')),
    NombreOriginal   VARCHAR(255) NULL,
    MimeType         VARCHAR(100) NULL,
    TamanoBytes      BIGINT       NULL,
    DuracionSeg      INT          NULL,
    HashSha256       CHAR(64)     NULL,
    Transcripcion    TEXT         NULL,
    Resumen          TEXT         NULL,
    Observaciones    TEXT         NULL,
    GeneradoPor      VARCHAR(10)  NOT NULL DEFAULT 'manual'
                     CHECK (GeneradoPor IN ('manual','ia','mixto')),
    ModeloIa         VARCHAR(80)  NULL,
    EstadoProceso    VARCHAR(12)  NOT NULL DEFAULT 'pendiente'
                     CHECK (EstadoProceso IN ('pendiente','procesando','completado','error')),
    FechaRegistro    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FechaModificacion TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FkRegistroDocEntidad   FOREIGN KEY (IdEntidad)   REFERENCES Entidad(IdEntidad)     ON DELETE RESTRICT,
    CONSTRAINT FkRegistroDocCanino    FOREIGN KEY (IdCanino)    REFERENCES Canino(IdCanino)       ON DELETE RESTRICT,
    CONSTRAINT FkRegistroDocSesion    FOREIGN KEY (IdSesion)    REFERENCES Sesion(IdSesion)       ON DELETE SET NULL,
    CONSTRAINT FkRegistroDocOperacion FOREIGN KEY (IdOperacion) REFERENCES Operacion(IdOperacion) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS IxRegistroDocCanino  ON RegistroDocumental (IdCanino, FechaHora);
CREATE INDEX IF NOT EXISTS IxRegistroDocSesion  ON RegistroDocumental (IdSesion);
CREATE INDEX IF NOT EXISTS IxRegistroDocEntidad ON RegistroDocumental (IdEntidad, FechaHora);

-- NULLS NOT DISTINCT: las etiquetas globales (IdEntidad NULL) tampoco se
-- pueden repetir, así los datos semilla no se duplican al re-ejecutar el script.
CREATE TABLE IF NOT EXISTS Etiqueta (
    IdEtiqueta INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdEntidad  INT NULL,
    Nombre     VARCHAR(60) NOT NULL,
    Color      VARCHAR(20) NULL,
    CONSTRAINT UqEtiqueta UNIQUE NULLS NOT DISTINCT (IdEntidad, Nombre),
    CONSTRAINT FkEtiquetaEntidad FOREIGN KEY (IdEntidad) REFERENCES Entidad(IdEntidad) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RegistroEtiqueta (
    IdRegistroDocumental INT NOT NULL,
    IdEtiqueta           INT NOT NULL,
    PRIMARY KEY (IdRegistroDocumental, IdEtiqueta),
    CONSTRAINT FkRegistroEtiquetaDoc      FOREIGN KEY (IdRegistroDocumental) REFERENCES RegistroDocumental(IdRegistroDocumental) ON DELETE CASCADE,
    CONSTRAINT FkRegistroEtiquetaEtiqueta FOREIGN KEY (IdEtiqueta)           REFERENCES Etiqueta(IdEtiqueta)                     ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RegistroIa (
    IdRegistroIa         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdCanino             INT          NOT NULL,
    IdEntidad            INT          NULL,
    IdRegistroDocumental INT          NULL,
    Especialidad         VARCHAR(50)  NOT NULL,
    Fecha                DATE         NOT NULL,
    Resultado            VARCHAR(50)  NULL,
    Confianza            INT          NULL,
    Observaciones        TEXT         NULL,
    ArchivoPath          VARCHAR(255) NULL,
    FechaRegistro        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FkRegistroIaCanino FOREIGN KEY (IdCanino)             REFERENCES Canino(IdCanino) ON DELETE RESTRICT,
    CONSTRAINT FkRegistroIaDoc    FOREIGN KEY (IdRegistroDocumental) REFERENCES RegistroDocumental(IdRegistroDocumental) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS IxRegistroIaCanino ON RegistroIa (IdCanino, Fecha);

-- =====================================================================
--  TRIGGERS FechaModificacion   (equivalen a ON UPDATE CURRENT_TIMESTAMP)
-- =====================================================================

CREATE OR REPLACE TRIGGER TrEntidadFechaModificacion
    BEFORE UPDATE ON Entidad FOR EACH ROW EXECUTE FUNCTION fn_fecha_modificacion();
CREATE OR REPLACE TRIGGER TrUsuarioFechaModificacion
    BEFORE UPDATE ON Usuario FOR EACH ROW EXECUTE FUNCTION fn_fecha_modificacion();
CREATE OR REPLACE TRIGGER TrCaninoFechaModificacion
    BEFORE UPDATE ON Canino FOR EACH ROW EXECUTE FUNCTION fn_fecha_modificacion();
CREATE OR REPLACE TRIGGER TrRegistroDocFechaModificacion
    BEFORE UPDATE ON RegistroDocumental FOR EACH ROW EXECUTE FUNCTION fn_fecha_modificacion();

-- =====================================================================
--  VISTAS DE APOYO A REPORTES E INDICADORES   (RF-15, RF-16)
-- =====================================================================

CREATE OR REPLACE VIEW VwCaninoVacunacion AS
SELECT c.IdCanino,
       MAX(v.FechaAplicacion) AS UltimaVacunacion,
       MIN(CASE WHEN v.FechaVencimiento >= CURRENT_DATE
                THEN v.FechaVencimiento END) AS ProximaVacunacion,
       SUM(CASE WHEN v.FechaVencimiento < CURRENT_DATE THEN 1 ELSE 0 END) AS VacunasVencidas
FROM Canino c
LEFT JOIN CaninoVacuna v ON v.IdCanino = c.IdCanino
GROUP BY c.IdCanino;

CREATE OR REPLACE VIEW VwBinomioVigente AS
SELECT b.IdBinomio, b.IdCanino, b.IdGuia, b.IdEntidad, b.FechaInicio,
       u.Nombre AS NombreGuia, c.Nombre AS NombreCanino, c.CodigoUnico
FROM Binomio b
JOIN Usuario u ON u.IdUsuario = b.IdGuia
JOIN Canino  c ON c.IdCanino  = b.IdCanino
WHERE b.FechaFin IS NULL;

CREATE OR REPLACE VIEW VwTimelineCanino AS
SELECT e.IdCanino, e.FechaHora, e.Categoria, e.Tipo, e.Titulo, e.Descripcion,
       e.Resultado, e.UbicacionTexto, e.Latitud, e.Longitud,
       u.Nombre AS RegistradoPor
FROM Evento e
LEFT JOIN Usuario u ON u.IdUsuario = e.IdUsuarioRegistra;

-- AGE() devuelve el intervalo exacto (años, meses, días) entre dos fechas;
-- reemplaza a TIMESTAMPDIFF de MySQL.
CREATE OR REPLACE VIEW VwCaninoDetalle AS
SELECT c.IdCanino, c.CodigoUnico, c.Nombre, c.Raza, c.Genero, c.Estado,
       c.FechaNacimiento,
       EXTRACT(YEAR  FROM AGE(CURRENT_DATE, c.FechaNacimiento))::INT AS EdadAnios,
       EXTRACT(MONTH FROM AGE(CURRENT_DATE, c.FechaNacimiento))::INT AS EdadMesesResto,
       (EXTRACT(YEAR  FROM AGE(CURRENT_DATE, c.FechaNacimiento)) * 12
        + EXTRACT(MONTH FROM AGE(CURRENT_DATE, c.FechaNacimiento)))::INT AS EdadMesesTotal,
       e.RazonSocial AS Entidad, p.Nombre AS Programa,
       u.Nombre AS GuiaActual, vv.UltimaVacunacion, vv.ProximaVacunacion,
       vv.VacunasVencidas
FROM Canino c
JOIN Entidad e            ON e.IdEntidad   = c.IdEntidad
LEFT JOIN ProgramaK9 p    ON p.IdPrograma  = c.IdPrograma
LEFT JOIN Usuario u       ON u.IdUsuario   = c.IdGuiaActual
LEFT JOIN VwCaninoVacunacion vv ON vv.IdCanino = c.IdCanino;

-- COUNT(...) FILTER (WHERE ...) cuenta solo las filas que cumplen la condición;
-- reemplaza a SUM(c.Estado = 'activo'), que en PostgreSQL no es válido.
CREATE OR REPLACE VIEW VwIndicadorEntidad AS
SELECT e.IdEntidad, e.RazonSocial,
       COUNT(c.IdCanino) FILTER (WHERE c.Estado = 'activo')        AS CaninosActivos,
       COUNT(c.IdCanino) FILTER (WHERE c.Estado = 'entrenamiento') AS CaninosEntrenamiento,
       COUNT(c.IdCanino) FILTER (WHERE c.Estado = 'descanso')      AS CaninosDescanso,
       COUNT(c.IdCanino) FILTER (WHERE c.Estado = 'incapacitado')  AS CaninosIncapacitados,
       COUNT(c.IdCanino) FILTER (WHERE c.Estado = 'retirado')      AS CaninosRetirados,
       COUNT(c.IdCanino)                                           AS CaninosTotal
FROM Entidad e
LEFT JOIN Canino c ON c.IdEntidad = e.IdEntidad
GROUP BY e.IdEntidad, e.RazonSocial;

-- =====================================================================
--  DATOS SEMILLA
-- =====================================================================

INSERT INTO Rol (Clave, Nombre, Descripcion, Ambito, EsFijo) VALUES
 ('super_admin',   'Super administrador',        'Administra todas las entidades del sistema.', 'global',  1),
 ('admin_entidad', 'Administrador institucional','Administra los recursos de su entidad.',      'entidad', 1),
 ('instructor',    'Instructor K9',              'Registra sesiones, evaluaciones y evidencia.','entidad', 1),
 ('guia_canino',   'Guia canino',                'Opera con su binomio y reporta actividad.',   'entidad', 1),
 ('veterinario',   'Veterinario',                'Registra atenciones y controles sanitarios.', 'entidad', 1)
ON CONFLICT DO NOTHING;

INSERT INTO ProgramaK9 (Clave, Nombre, Descripcion, Icono, Color, EsFijo) VALUES
 ('drogas','Deteccion de Drogas','Especializacion olfativa para identificacion de sustancias ilicitas.','bi-eyedropper-fill','#ef4444',1),
 ('explosivos','Deteccion de Explosivos','Deteccion de artefactos explosivos, municion y materiales peligrosos.','bi-lightning-charge-fill','#f97316',1),
 ('rescate','Busqueda y Rescate','Busqueda de personas en escombros, avalanchas y emergencias.','bi-life-preserver','#22c55e',1),
 ('seguridad','Seguridad y Proteccion','Patrullaje, proteccion de instalaciones y control de perimetros.','bi-shield-fill','#3b82f6',1),
 ('rastreo','Rastreo y Seguimiento','Seguimiento de rastros y apoyo en investigaciones.','bi-compass-fill','#8b5cf6',1),
 ('personas','Deteccion de Personas','Localizacion de personas vivas o fallecidas en grandes areas.','bi-people-fill','#06b6d4',1),
 ('multiple','Multiple / Integral','Combina mas de una especialidad operativa en un mismo binomio.','bi-collection-fill','#b8860b',1)
ON CONFLICT DO NOTHING;

INSERT INTO Etiqueta (IdEntidad, Nombre) VALUES
 (NULL,'Obediencia'), (NULL,'Salto'), (NULL,'Reporte de objeto'),
 (NULL,'Permanencia'), (NULL,'Socializacion'), (NULL,'Evaluacion')
ON CONFLICT DO NOTHING;
